version: '3'

services:

  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm init -y && npm install express prom-client && node server.js"
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=najafathimapt123@gmail.com
      - GF_SMTP_PASSWORD=lkxt eoxz izuz mgqe
      - GF_SMTP_FROM_ADDRESS=najafathimapt123@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "8080:8080"
